# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 서도경
title: Java 백엔드 엔지니어
email: dgseo8981@gmail.com
website: https://seogineer.tistory.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username: seogineer
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: seogineer
linkedin_username: 도경-서-863031200
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  - 3년차 웹 개발자입니다. 현재는 Java 백엔드 개발자로 일하고 있습니다.
#  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.
#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Backend
        description: |
          - Java
          - Spring Boot, 
          - Spring Data JPA, Querydsl
          - Maven
          - Git, Sourcetree
          - MySQL, MariaDB

      - layout: left
        title: DevOps
        description: |
          - Ubuntu Linux

      - layout: left
        title: Frontend
        description: |
          - HTML, CSS, Javascript

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 롯데푸드 웹사이트 리뉴얼
        caption: 2021.08 ~ 2021.09
        sub_title: 넥스트컬쳐
        description: |
          - 컨텐츠룸(롯데푸드CF, 보도자료, 레시피, 이벤트)
          - 고객지원(공지사항)
          - Java 11, Spring Boot, Spring Data JPA, QueryDSL, MariaDB, Linux, GitLab, IntelliJ Ultimate

      - layout: left
        title: 롯데칠성 음료학교 웹사이트 리뉴얼
        caption: 2021.04 ~ 2021.08
        sub_title: 넥스트컬쳐
        description: |
          - 공지사항 게시판
          - 뉴스레터 게시판
          - 포트폴리오 게시판
          - Q&A 게시판
          - FAQ 게시판
          - 신제품 인큐베이팅 게시판
          - 인큐베이팅 리그 게시판
          - 소식 구독
          - 관리자 화면(댓글, 인큐베이팅 목록 조회)
          - 개인정보 보안 심의 대응 개발(개인정보 마스킹, 개인정보 이용 및 접근 로그, 개인정보 일괄 처리)
          - Java 11, Spring Boot, Spring Data JPA, QueryDSL, MariaDB, Linux, GitLab, IntelliJ Ultimate
      
      - layout: left
        title: 우리은행 한국교직원공제회 외화자금운용시스템 구축
        caption: 2020.07 ~ 2020.10
        sub_title: 코아뱅크
        # link: github.com/sproogen
        # link_text: Project Website
        # additional_links:
          # - title: sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
        description: | # this will include new lines to allow paragraphs
          - 통화코드관리
          - BIC코드관리
          - 국가코드관리
          - CUT-TIME관리/연장
          - 인터페이스전문관리
          - 환율정보조회
          - 공통정보항목명세
          - 환율 정보 수신
          - Java, Javascript, 전자정부프레임워크, Tode, Oracle19c, Windows10

      - layout: left
        title: 우리은행 인도 첸나이 SCORE(글로비스) 구축
        caption: 2020.02 ~ 2020.07
        sub_title: 코아뱅크
        description: |
          - 업체 코드 관리 화면
          - CDK-Plus SWIFT 전문 변환 기능 개선
          - Java, Javascript, Oracle, Orange, Filezila, UltraEdit, AIX, Windows10

      - layout: left
        title: 하나은행 수출입 고도화 프로젝트
        caption: 2019.03 ~ 2020.01
        sub_title: 코아뱅크
        description: |
          - EDMS(Electronic Document Management System) 연동
          - 내국신용장 개설 조회
          - NEGO 서류 추가 발송
          - 통합기일조회(수입서류인도 대상 조회 추가)
          - 수출입MAIN 화면(환율 우대, 수수료 우대 탭)
          - Javascript, Xframe, Proframe, Oracle, Windows10

      - layout: left
        title: 하나은행 글로벌검사정보 시스템 고도화 프로젝트
        caption: 2018.10 ~ 2019.01
        sub_title: 코아뱅크
        description: |
          - 공지사항 게시판 작성자 검색 기능 버그 수정
          - 권한에 따른 게시판 탭 표시
          - 전용 게시판 이름 변경
          - KEB 로고 최신화
          - 언어 코드 추가(일본어, 영어)
          - Javascript, JSP, UNIX, Tibero, UltraEdit, Windows7

      - layout: left
        title: 삼성전자 P-PJT 설비제어공사
        caption: 2017.03 ~ 2017.05
        sub_title: 에스아이티
        description: |
          - HMI 화면 개발 및 테스트
          - 납품 단말 유지보수
          - C, WinCC OA, Windows7

  - title: Experience
    layout: list
    content:
      - layout: left
        title: 넥스트컬쳐
        caption: 2021.04 ~ 2021.09
        sub_title: 자바 백엔드 개발자
        quote: >
          웹에이전시
        description: |
          - 롯데푸드 웹사이트 리뉴얼
          - 롯데칠성 음료학교 웹사이트 리뉴얼
          - Java 11, Spring Boot, Spring Data JPA, QueryDSL, MariaDB, Linux, GitLab, IntelliJ 환경에서 개발 경험

      - layout: left
        title: 코아뱅크
        caption: 2018.09 ~ 2020.11
        sub_title: 웹 개발자
        quote: >
          금융 SI
        description: | 
          - 우리은행, 하나은행 SI 프로젝트 참여
          - Xframe, 전자정부프레임워크, Oracle 환경에서 개발 경험

      - layout: left
        title: 에스아이티
        caption: 2017.03 ~ 2017.05
        sub_title: 인턴
        quote: >
          공장자동화
        description: | 
          - 삼성전자 P-PJT 설비제어공사 참여
          - 지멘스 S7, WinCC OA 환경에서 Human-Machine Interface 개발 경험

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 비트교육센터
        caption: 2018.02 ~ 2018.08
        sub_title: 자바 기반 웹&앱 개발자 양성과정
        quote: >
          엄진영 강사님의 교육
        description: | # this will include new lines to allow paragraphs
          - 자바, 스프링을 이용한 웹 애플리케이션 제작 교육

  - title: Certificate # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 정보처리기사
        sub_title: 한국산업인력공단
        description: | # this will include new lines to allow paragraphs
          - 2016.07.15 취득

#  - title: A Little More About Me
#    layout: text
#    content: | # this will include new lines to allow paragraphs
#      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#      - Rock climbing
#      - Gaming
#      - Knitting
#      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

#      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
